### PR TITLE
fix PutVersionedSecrets

### PR DESCRIPTION
**Pull request by bLamarche413**
A forward slash was missing from the secret path for PutVersionedSecrets. I added the slash, and added a test which passes with the forward slash and fails without it.

### CODE REVIEW

**Comment by jprobinson** [comment]
Hrm. It appears travis is having issues with NYTimes vs nytimes. I'll see what we can do.

**Comment by jprobinson** [comment]
Ugh, it appears travis is even ignoring 'import' directives. I just added one to doc.go on master and it ignored it.

I'll see if I can move this over to cloud.drone.io.

**Comment by jprobinson** [comment]
OK boss, I've moved master over to cloud.drone.io. Mind pulling from master?

**Comment by bLamarche413** [comment]
I had credentials locally that the test doesn't appear to have in the drone setup, which was making the new test pass. I'm going to try to use local secrets instead so it can pass anywhere.

**Pull request merged**
