### PR TITLE
Backoff retry for login - improvements

### PR DESCRIPTION
**Pull request by soeirosantos**
This PR addresses the comments in https://github.com/nytimes/gcp-vault/pull/27

### CODE REVIEW

**Comment by oliver-nyt** [comment]
I noticed there are no tests run automatically by drone - can this be fixed please?

**Comment by soeirosantos** [comment]
It seems that tests are being executed here: https://cloud.drone.io/nytimes/gcp-vault/49/1/3

**Comment by oliver-nyt** [comment]
Hmm, that's odd that they aren't listed in the integrations.

**Comment by soeirosantos** [comment]
@patrick-nyt, I think we are good to go - can we get this merged? Thanks!

**Pull request merged**
